name: End-to-end tests and deploy

on:
  push:
    branches:
      - main  # ou o branch que você usa como principal

permissions:
  contents: write  # 👈 garante que o deploy possa escrever no branch gh-pages

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          command: npm run test

      # 👉 Só faz deploy se os testes passarem e for o branch principal
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 👈 pasta onde está seu index.html